### ISSUE TITLE
Constraint soal "hadiah" bab divide and conquer mungkin membingungkan

### ISSUE THREAD

**Issue by thegalang** [ia-toki/Training-TLX#11]
contraints a,b,c pada soal "hadiah":
A (0 ≤ A ≤ 1 x 10^3), B (0 ≤ B ≤ 2 x 10^4), dan C (0 ≤ C ≤ 3 x 10^5).

maka a,b,c dapat bernilai 0, maka tc seperti dibawah ini valid dong: (misal N itu sebuah bilangan asli)
0 0 0
0 0 N
N 0 0

padahal, kalau dihitung, akan didapat hasil 0^0, nilai tak terdefinisi

btw Case 12 tolong dong di cek, rasanya itu salah tc, karena program saya yang AC (bukan dengan euler phi) mendapat WA di case tersebut

**Comment by gyosh** [comment]
Benar, ada kesalahan kasus uji. Sekarang seharusnya sudah benar.
Untuk masalah batasan kurang jelas, saya sudah tambahkan kalimat bahwa A^(B^C) pasti terdefinisi sebagai bilangan bulat.

Terima kasih atas masukannya!
