### ISSUE TITLE
Soal "Quadtree 1 : Pengodean" Jawaban sudah benar namun dianggap salah

### ISSUE THREAD

**Issue by itsdimasr** [ia-toki/Training-TLX#16]
Quadtree I: Pengodean
Link Soal :
[https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/18/problems/75/](url)
Submission saya :
[https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/18/submissions/programming/183603](url)

Jawaban saya sudah benar, bahkan sudah sesuai dengan 4 sample test data yang ditampilkan. Setelah saya teliti, jawaban juga sudah persis, sudah saya cek spasi, enter, dsb.. namun tetap wrong answer kecuali satu jawaban yang di sample no 3..
waktu dan memory juga tidak ada masalah
mohon bantunannya, terima kasih

**Comment by thegalang** [comment]
disini bukan untuk bertanya tentang letak kesalahan pada program, dan hanya digunakan untuk melaporkan kesalahan test case pada program juri, coba gunaak grup facebook https://www.facebook.com/groups/olimpinfo/
