### ISSUE TITLE
Testcase TLX chapter 9, Jawbreaker 5

### ISSUE THREAD

**Issue by prabowoD** [ia-toki/Training-TLX#2]
di deskripsi tertulis (4 ≤ M, N ≤ 25), tapi saat dicoba assert kena verdict Runtime Error
tanpa assert Wrong Answer

Sepertinya tc yang sama juga dipakai untuk TLC Bab 8C Jawbreaker 5 juga

**Comment by gyosh** [comment]
Hmm baru tau ada repo ini. Kayaknya ini repo yg ga jadi dipake?
cc @dragoon20 @fushar @alijaya 

@prabowoD secara mengejutkan testcase buat soal itu semuanya salah (tc buat soal lain!)
sudah diperbaiki, dan terima kasih atas laporannya. Untuk ke depannya, silakan lapor di https://github.com/ia-toki/training-gate-id

**Comment by prabowoD** [comment]
Thanks :D uda bisa Accepted

btw ini masalah lain. Apakah deskripsinya bisa diganti sedikit? Sempat bingung nyari Jawbreaker versi sebelumnya (karena lupa cara hitung poin). Mungkin bisa ditambah link soalnya?

**Comment by gyosh** [comment]
Oke akan dikerjakan nanti

**Comment by alijaya** [comment]
@gyosh : ini khusus buat laporan soal2 selain yang kamu buat kurikulumnya :-?... *either kontes, osn dll... ._.
