### ISSUE TITLE
Deskripsi soal "Membeli Beras" ambigu

### ISSUE THREAD

**Issue by circleous** [ia-toki/Training-TLX#20]
Soal: https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/16/problems/64/
Untuk batasan N, tercetak  dua kali
```
Batasan
- 1 ≤ N ≤ 100
- 1 ≤ N ≤ 1.000
- 1 ≤ Wi, Ci ≤ 1.000
- 1 ≤ X ≤ 100.000
```

**Comment by namakuanshar** [comment]
Saya pake N : integer, aman2 aja :)

**Comment by gyosh** [comment]
Terima kasih atas laporannya, soal telah diperbaiki
