### ISSUE TITLE
Pelulangan, Pola I dan Statistika Sederhana jawaban benar namun selalu WA

### ISSUE THREAD

**Issue by agentnine** [ia-toki/Training-TLX#22]
Statistika sederhana
var
  a,i,max,min: longint;
  j: array[1..100] of longint;
  
begin
  readln(a);
  for i:= 1 to a do begin
  read(j[i]);
  end;
  
  max := j[1];
  for i:= 2 to a do
  if j[i] > max then
  max := j[i];
  
  min := j[1];
  for i:= 2 to a do
  if j[i] < min then
  min := j[i];
  
  write(max, ' ', min);
end.

Pola I
var
  i,a,b: integer;
begin
  readln(a,b);
  for i := 1 to (a-1) do
  if (i = a) then begin
    if (i mod b = 0) then write('* ') else write(i, ' ');
  end;
  
  if (a mod b = 0) then write('*') else write(i);
end.

**Comment by circleous** [comment]
https://github.com/ia-toki/Training-TLX#pastikan-anda-mencetak-baris-baru-pada-akhir-keluaran

**Comment by agentnine** [comment]
perjelas dong kak maaf saya pemula @circleous

**Comment by agentnine** [comment]
ohh sudah paham thx a lot @circleous
