### ISSUE TITLE
Pemrograman Dasar Chapter 5 Problem F - Floor dan Ceiling: Output dan jawaban sudah sesuai spek tapi masih saja ada Wrong Answer

### ISSUE THREAD

**Issue by aramadsanar** [ia-toki/Training-TLX#23]
Dear Team TLX,

Saya ingin melaporkan adanya kemugnkinan error pada Pemrograman Dasar Chapter 5 Problem F - Floor dan Ceiling (link soal: https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/5/problems/11/ dan link submission: https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/5/submissions/programming/239564), dimana output dan jawaban sudah sesuai dengan spek yang diberikan di soal, tetapi ketika dirun di judge TLX menghasikan 6 Wrong Answers dari 10 test cases. Saya sudah coba sendiri dan baik pada kasus angka positif dan negatif output nya memenuhi spek dan kaidah yang berlaku. Mohon diperbaiki secepatnya karena saya tidak dapat lanjut ke bab selajnutnya apabila issue ini belum diselesaikan.

Sebagai lampiran, berikut saya lampirkan source code saya untuk solusi dari soal yang saya laporkan: http://ideone.com/sw3V6g

Terima Kasih

**Comment by fushar** [comment]
Kasus uji untuk soal ini sudah benar. Silakan perbaiki solusi Anda; masih ada salahnya.
