### ISSUE TITLE
Chapter 10 TLX: Tukang Sulap - (Kesalahan Batasan)

### ISSUE THREAD

**Issue by YuAndyTX** [ia-toki/Training-TLX#24]
Permisi mau tanya,
Pada Soal Tukang Sulap, dinyatakan bahwa batasan nya berupa

> 1 ≤ N ≤ 1.000

Tetapi jika dideklarasi array dengan indeks maksimum 1100, akan terjadi **RTE** 
**(Id Submission: 248217)**
Jika dinaikkan indeks tersebut menjadi 2000, Accepted didapatkan
**(Id Submission: 248218)**
Apakah memang kesalahan program? atau dari Test Case juri?

[Link Soal](https://training.ia-toki.org/training/curriculums/1/courses/1/chapters/13/problems/46/)

Terima Kasih sebelumnya

**Comment by gyosh** [comment]
RTE nya karena:
```
int data[2][1100];
```

Sementara pada program diakses `data[1][...]` dan `data[2][...]`
Sudah accepted kalau di-declare menjadi `data[3][1100]`
