### ISSUE TITLE
Pemrograman Dasar-Ekspresi dan I/O-Bebek untuk Teman

### ISSUE THREAD

**Issue by mrizkii7** [ia-toki/Training-TLX#25]
Saya sudah mengerjakan soal terssebut dengan kode sbb

program bebek;
var
	N : integer;
	M : integer;
	masingmasing : integer;
	bersisa : integer;
begin
	read(N, M);
	masingmasing := N div M;
	bersisa := N mod M;
	writeln('masing-masing ', masingmasing);
	writeln('bersisa ', bersisa);
end.

namun, masih wrong answer, dan mendapatkan 80 pts, mohon penjelasan salah disebelah mana?

**Comment by gyosh** [comment]
Gunakan tipe data integer 32 bit (longint)
