### ISSUE TITLE
Pemrograman Kompetitif Dasar - Greedy : Perkalian Skalar

### ISSUE THREAD

**Issue by 0load** [ia-toki/Training-TLX#26]
Kesalahan untuk keterangan soal `x₁y₁ + x₁y₂ + x₃y₃ + ... + xₙyₙ` seharusnya `x₁y₁ + x₂y₂ + x₃y₃ + ... + xₙyₙ`

**Comment by gyosh** [comment]
Terima kasih atas laporannya.
Sudah diperbaiki.
