### ISSUE TITLE
Soal Burung beo selalu wrong answer

### ISSUE THREAD

**Issue by jeffersonjt** [ia-toki/Training-TLX#27]
Data test selalu salah dan hanya bisa 60pts terus.
Saya pakai pascal dan sudah mencoba mencari semua kesalahan tetapi program saya masih berfungsi sesuai yang diminta soal. Tetapi verdict juri selalu wrong answer.

ini code soal saya tolong kasih tahu kalau ternyata salah:
program soal3;
uses crt;
var
kalimat:string;
begin
readln(kalimat);
writeln(kalimat);
end.

**Comment by fushar** [comment]
Test data sudah benar.

Petunjuk: coba kamu cek berapa maksimum karakter pada tipe data `string`:

https://www.freepascal.org/docs-html/rtl/system/length.html
