### ISSUE TITLE
Typo pada Soal Knapsack di baba DP

### ISSUE THREAD

**Issue by mamat-rahmat** [ia-toki/Training-TLX#30]
url : https://training.ia-toki.org/training/curriculums/1/courses/11/chapters/55/problems/251/

tertulis
1 ≤ Wi, Hi ≤ 2.000, untuk 1 ≤ i ≤ N
seharusnya
1 ≤ Wi, Hi ≤ 2.000, untuk 1 ≤ i ≤ K

**Comment by gyosh** [comment]
oke sudah diperbaiki, terima kasih atas laporannya!
