### ISSUE TITLE
Kesalahan sample testcase pada soal DP - Knapsack

### ISSUE THREAD

**Issue by devil-gum** [ia-toki/Training-TLX#40]
https://training.ia-toki.org/training/curriculums/1/courses/11/chapters/55/problems/251/

Output program untuk sample testcase 1 telah sesuai dengan yang tertulis di laman soal, namun menghasilkan verdict Wrong Answer saat disubmit.

![scrs11](https://user-images.githubusercontent.com/31818706/38429714-6489afaa-39e9-11e8-8e35-5e50994fd062.PNG)

**Comment by gyosh** [comment]
ok sudah diperbaiki, terima kasih atas laporannya!
