### ISSUE TITLE
Course 02 Chapter 09: Perkenalan Graph Soal D. Jalan Tol Menuju Roma [Jawaban Bermasalah]

### ISSUE THREAD

**Issue by hockyy** [ia-toki/Training-TLX#45]
Jawaban **sample** milik grader bermasalah
Seharusnya, menurut sample yang ditampilkan jawabannya 3
Saat di output 3, grader menilai sample salah.
:/

**Comment by gyosh** [comment]
Oke sample sudah diperbaiki.
Terima kasih atas laporannya!
