### ISSUE TITLE
Masalah Apostrophe di Kuis Variabel dan Tipe Data (Chapter 2) pada No 3

### ISSUE THREAD

**Issue by mamat-rahmat** [ia-toki/Training-TLX#6]
Pada soal tersebut disebutkan :

Berikut ini adalah karakter-karakter yang dapat direpresentasikan oleh tipe data char, kecuali ....
a. !
b. ?
c. "
d. '
e. Pilihan a sampai dengan d salah, karena semuanya dapat direpresentasikan

Sebetulnya apostrophe atau kutip satu (') dapat direpresentasikan oleh tipe data char dengan menuliskannya dua kali seperti disebutkan dalam [dokumentasi string di Free Pascal](http://www.freepascal.org/docs-html/ref/refse8.html)
> The single quote character can be embedded in the string by typing it twice. The C construct of escaping characters in the string (using a backslash) is not supported in Pascal. 

Namun pada materi tidak dituliskan mengenai hal ini. 

Banyak kasus dimana orang mencoba memprogramnya dengan mencetak apostrophe atau mengisinya ke variabel char namun tidak berhasil, lalu mengasumsikan tidak bisa. Setelah jawaban di verdict salah, akhirnya dipilih jawaban E dan dilewati begitu saja sehingga pengguna tidak mendapat pelajaran yang sesungguhnya.

**Comment by mamat-rahmat** [comment]
cc @gyosh

**Comment by gyosh** [comment]
Oh saya juga baru tahu.
Baiklah soal itu telah kami hilangkan.

Terima kasih atas laporan ini.

**Comment by mamat-rahmat** [comment]
Sebetulnya tidak mengapa tetap ada, tetapi perlu dijelaskan di slide bahwa apostrophe adalah karakter yg harus diperlakukan khusus di string (ditulis 2x). Tapi ya terserah maintainer saja :)
