### ISSUE TITLE
Time limit terlalu ketat untuk soal "Binary Search - Sorted"

### ISSUE THREAD

**Issue by circleous** [ia-toki/Training-TLX#7]
Untuk C/C++ gak ada masalah, tapi untuk python time limit kurang fair.

[1] https://www.facebook.com/groups/olimpinfo/permalink/10155400108105961/

**Comment by circleous** [comment]
Ada kemungkinan ga cuma di soal ini aja yang time limitnya tidak fair, belum coba ke soal lain sih. Tapi  literally input testcase itu gak sedikit dan stdin/stdout CPython itu lambat.

**Comment by gyosh** [comment]
@circleous Setelah diuji coba, time limit dinaikkan menjadi 1000 ms
