### ISSUE TITLE
Time Limit pada Soal "Segiempat Aritmatika"

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/Training-TLX#8]
Apakah time limit untuk soal [Segiempat Aritmatika](https://training.ia-toki.org/problemsets/11/problems/35/) terlalu ketat?

Untuk soal yang sama, saya mendapatkan Accepted di [SPOJ](http://www.spoj.com/problems/NPC2014H/) dengan menggunakan [source code](https://training.ia-toki.org/problemsets/11/submissions/programming/160004) yang sama.

**Comment by gyosh** [comment]
Setelah dicoba, solusi juri berjalan ~300 ms
Berhubung ini time limit official dari NPC, tim TLX tidak menaikkan time limit karena 3x time limit sudah cukup adil.

Coba optimisasi konstanta solusi Anda, misalnya menggunakan array sebagai stack, bukan vector/stack pada STL.

Terima kasih atas laporan ini. Orang2 seperti Anda yang membuat komunitas Olimpiade Informatika Indonesia lebih baik.
