### ISSUE TITLE
Testcase untuk Soal "Sungai Biner"

### ISSUE THREAD

**Issue by prabowo02** [ia-toki/Training-TLX#9]
Apakah testcase untuk soal [Sungai Biner](https://training.ia-toki.org/problemsets/44/problems/220/) sudah benar?

Saya terkena assertion error saat mengecek constraint, dan untuk beberapa testcase juga terkena Wrong Answer walaupun saya sudah cukup yakin.
[Source code](https://training.ia-toki.org/problemsets/44/submissions/programming/161195).

**Comment by fushar** [comment]
Terima kasih atas laporannya. Ternyata memang terdapat beberapa kasus uji yang invalid. Sudah diperbaiki. Silakan submit ulang.
